modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="thesuffering"
version="1.0.0"
displayName="TheSuffering"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Dodobear, MCreator"

[[dependencies.thesuffering]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




